# Generated by Django 3.1.4 on 2021-01-03 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='period',
            field=models.CharField(default='1d', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ratio',
            field=models.CharField(default=0.8, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ticker',
            field=models.CharField(default='AAPL', max_length=20),
            preserve_default=False,
        ),
    ]
